[package]
name = "es_mapping"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["indexmap"] }
macros = { path = "./macros" }

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"
